# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        carre: # Nom du filtre
            quality: 90 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                scale:
                    dim: [ 200, 200 ]
        description: # Nom du filtre
            quality: 90 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                scale:
                    dim: [ 500, 500 ]